### ISSUE TITLE
Cannot compile on macOS 15.4

### ISSUE THREAD

**Issue by functionistic** [roddyyaga/pg_query-ocaml#20]
Compiling on macOS 15.4 using `make` yields - amongst other warnings:
```
src/postgres/src_port_snprintf.c:374:1: error: static declaration of 'strchrnul' follows non-static declaration
  374 | strchrnul(const char *s, int c)
      | ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_string.h:198:9: note: previous declaration is here
  198 |         strchrnul(const char *__s, int __c);
      |         ^
src/postgres/src_port_snprintf.c:438:27: warning: 'strchrnul' is only available on macOS 15.4 or newer [-Wunguarded-availability-new]
  438 |                         const char *next_pct = strchrnul(format + 1, '%');
      |                                                ^~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_string.h:198:9: note: 'strchrnul' has been marked as being introduced in macOS 15.4 here, but the deployment target is macOS 15.0.0
  198 |         strchrnul(const char *__s, int __c);
      |         ^
src/postgres/src_port_snprintf.c:438:27: note: enclose 'strchrnul' in a __builtin_available check to silence this warning
  438 |                         const char *next_pct = strchrnul(format + 1, '%');
      |                                                ^~~~~~~~~
  439 |
  440 |                         /* Dump literal data we just scanned over */
  441 |                         dostr(format, next_pct - format, target);
  442 |                         if (target->failed)
  443 |                                 break;
  444 |
  445 |                         if (*next_pct == '\0')
  446 |                                 break;
  447 |                         format = next_pct;
      |
1 warning and 1 error generated.
gmake[1]: *** [Makefile:174: src/postgres/src_port_snprintf.o] Error 1
make: *** [all] Error 1
```
This can be mitigated by pulling the latest libpg_query sources from their 17-latest branch. (see [CHANGELOG](https://github.com/pganalyze/libpg_query/blob/9ac12d29f2ffc0e49de8f4239223d50aaccd1549/CHANGELOG.md?plain=1#L8))
